var annotated_dup =
[
    [ "arrow", "classarrow.html", "classarrow" ],
    [ "ArrowShooter", "class_arrow_shooter.html", "class_arrow_shooter" ],
    [ "Blade", "class_blade.html", "class_blade" ],
    [ "BoundController", "class_bound_controller.html", "class_bound_controller" ],
    [ "BulletHit", "class_bullet_hit.html", "class_bullet_hit" ],
    [ "cameraController", "classcamera_controller.html", "classcamera_controller" ],
    [ "cameraFollow", "classcamera_follow.html", "classcamera_follow" ],
    [ "ChangeLevel", "class_change_level.html", "class_change_level" ],
    [ "characterSoundManager", "classcharacter_sound_manager.html", "classcharacter_sound_manager" ],
    [ "DatabaseManager", "class_database_manager.html", "class_database_manager" ],
    [ "destroyMe", "classdestroy_me.html", "classdestroy_me" ],
    [ "dieSoundManager", "classdie_sound_manager.html", "classdie_sound_manager" ],
    [ "enemyDamage", "classenemy_damage.html", "classenemy_damage" ],
    [ "EnemyHealth", "class_enemy_health.html", "class_enemy_health" ],
    [ "enemyMovementController", "classenemy_movement_controller.html", "classenemy_movement_controller" ],
    [ "HighScore", "class_high_score.html", "class_high_score" ],
    [ "HighScoreScript", "class_high_score_script.html", "class_high_score_script" ],
    [ "laserDoorTrap", "classlaser_door_trap.html", "classlaser_door_trap" ],
    [ "LevelManager", "class_level_manager.html", "class_level_manager" ],
    [ "MainMenu", "class_main_menu.html", "class_main_menu" ],
    [ "movingPlatform", "classmoving_platform.html", "classmoving_platform" ],
    [ "PauseMenu", "class_pause_menu.html", "class_pause_menu" ],
    [ "playerController", "classplayer_controller.html", "classplayer_controller" ],
    [ "playerHealth", "classplayer_health.html", "classplayer_health" ],
    [ "projectileController", "classprojectile_controller.html", "classprojectile_controller" ],
    [ "reloadBoundOfMap", "classreload_bound_of_map.html", "classreload_bound_of_map" ],
    [ "reloadTrap", "classreload_trap.html", "classreload_trap" ],
    [ "ScoreCanvas", "class_score_canvas.html", "class_score_canvas" ],
    [ "toggleObject", "classtoggle_object.html", "classtoggle_object" ],
    [ "toggleTarget", "classtoggle_target.html", "classtoggle_target" ],
    [ "trapController", "classtrap_controller.html", "classtrap_controller" ],
    [ "usebleSwitch", "classuseble_switch.html", "classuseble_switch" ],
    [ "Volume", "class_volume.html", "class_volume" ]
];